### ISSUE TITLE
Colector Not Starting

### ISSUE THREAD

**Issue by nbaillie** [logicmonitor/docker_lm_collector#22] opened 2018-07-20 09:43 UTC
Using a compose file like bellow on Swarm i get the error also bellow, when using the image "logicmonitor/collector:latest" from docker hub.

```
version: '3.2'
services:
  automated01:
    image: logicmonitor/collector:latest
    restart: always
    environment:
      account: 'xxxxx'
      access_id: 'xxxxx'
      access_key: 'xxxxx'
      collector_group: 'xxxxx'
      collector_size: "small"
      description: "xxxxx"
      cleanup: "true"
```

docker logs 5c2a2e10a2f8
DEBUG:root:finding collector Demo Server Collector
Traceback (most recent call last):
  File "/collector/startup.py", line 50, in <module>
    main()
  File "/collector/startup.py", line 46, in main
    startup(client, params)
  File "/collector/startup.py", line 14, in startup
    f = collector.find_collector(client, params)
  File "/collector/collector.py", line 100, in find_collector
    return find_collector_by_description(client, params)
  File "/collector/collector.py", line 142, in find_collector_by_description
    ' calling get_device_list: ' + str(e) + '\n'
UnboundLocalError: local variable 'e' referenced before assignment

**Comment by woz5999** [comment] 2018-07-20 16:11
@nbaillie I pushed a fix for the null reference errors you're seeing; however, the bad variable assignment is occurring AFTER you're hitting errors retrieving the collector list from your account. go ahead and give it a try with the build and you should be able to get meaningful error messages to figure out the true root cause.

**Comment by nbaillie** [comment] 2018-07-30 10:50
@woz5999 looks like the debug fix is good, i can now see it must be a auth issue with my api creds.

`DEBUG:root:finding collector Demo Server Collector
ERROR:root:Error 1401 calling get_collector_list: Authentication failed
DEBUG:root:finding collector Demo Server Collector
DEBUG:root:finding collector Demo Server Collector 
ERROR:root:Error 1401 calling get_collector_list: Authentication failed
ERROR:root:Error 1401 calling get_collector_list: Authentication failed`

**Comment by skt44** [comment] 2018-08-13 23:34
@nbaillie API tokens associated with a role that has read access to a single Collector group should already be able to make a request to get_collector_list - the result will just include the Collectors in that single group.

**Closed** 2019-06-20 14:27 UTC
